name: Compilar fork_win.exe

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Instalar compilador para Windows
      run: sudo apt-get update && sudo apt-get install -y mingw-w64

    - name: Compilar EXE para Windows
      run: |
        # -static para que no pida DLLs externas
        # -mwindows para que sea invisible (sin consola)
        x86_64-w64-mingw32-gcc -static fork_win.c -o fork_win.exe -mwindows
        x86_64-w64-mingw32-strip fork_win.exe

    - name: Commit y Push del ejecutable
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add fork_win.exe
        # Limpieza: eliminamos rastros de otros nombres antiguos si los hubiera
        git rm fork.elf fork.exe --ignore-unmatch 
        git commit -m "Update compiled fork_win.exe" || exit 0
        git push
