name: Compilar Solo para Windows

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Instalar compilador para Windows
      run: sudo apt-get update && sudo apt-get install -y mingw-w64

    - name: Compilar EXE para Windows
      run: |
        # Usamos el compilador cruzado para generar el .exe
        x86_64-w64-mingw32-gcc -static fork.c -o fork.exe
        # Limpiamos el archivo para que pese menos
        x86_64-w64-mingw32-strip fork.exe

    - name: Commit y Push del ejecutable
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add fork.exe
        # El comando git rm elimina el .elf del repo si existía antes
        git rm fork.elf --ignore-unmatch 
        git commit -m "Update compiled fork.exe" || exit 0
        git push
