name: Compilar Solo Linux ELF

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Compilar ELF para Linux
      run: |
        # Compila fork.c de forma estática para que funcione en cualquier Linux
        gcc -static fork.c -o fork.elf
        # Limpia el archivo de símbolos innecesarios para que pese menos
        strip fork.elf
        chmod +x fork.elf

    - name: Commit y Push del binario
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add fork.elf
        git commit -m "Update compiled fork.elf" || exit 0
        git push
